spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jdbc
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true